### ISSUE TITLE
Migrating Data from SFG - Windows batch script issue

### ISSUE THREAD

**Issue by geethasm** [IBM/pem-utilities#2]
Hi Team,

The packaged migrating tool in the github has an issue in the run.bat script. We are getting following error during execution of the script. 
![PEM_MigratingtoSFG_runbatchscript](https://user-images.githubusercontent.com/46224375/72322076-6c369980-36cb-11ea-9206-092a2185fa69.JPG)

Regards,
Geetha

**Comment by anshulga** [comment]
The issue has been resolved. Please download the latest release binary for the fix.
