### ISSUE TITLE
Migration tool Import verification unsuccessful 

### ISSUE THREAD

**Issue by geethasm** [IBM/pem-utilities#3]
[PEMMigrationImport_supportdoc.docx](https://github.com/IBM/pem-utilities/files/4553370/PEMMigrationImport_supportdoc.docx)
Hi Team,
I used the SFGPEM Migration data tool, extracting was success and could verify the result. Import also was success, but when I am verifying the output in the PR SFTP configuration, I don't see the imported data configuration in PR. 

Attached document contains the screen shots of the import part results.
Request to let me know where am I going wrong.
Regards,
Geetha
Geetha_sathyamurthy@in.ibm.com
+919686699018

**Comment by anshulga** [comment]
@geethasm There is not enough information in the ticket to troubleshoot the issue. I suggest you to review how the partner was configured in SFG to use SFTP protocol and see if it matches with the type of configuration created by PEM's out-of-box SFTP activity during partner onboarding process.

I am not sure why the tool reports the import as success when it was unable to identify the SFTP configuration for the partner and create it in Partner Repository. I need details on how the partner has been configured in B2BI/SFG to be able to replicate the behavior.

**Comment by geethasm** [comment]
Hi Anshul,

We picked up the partners from the existing CSRA client test environment,
where partners were created through PEM activity. so that we see  SFG
configuration is good to our knowledge. A new context was created to see
the PEM import is successful.

Attached the PEMMig_diagram of how we were testing PEMmigration tool for
extracting and importing into PEM. Also attached the PR and MRM trace log,
these log files are huge, hence I share only 2 log file, let me know which
and other docs to be shared.
 PRServer_trace.log
<https://drive.google.com/file/d/13UOq4GnTmJCfPjiXENvSTfn-00QfN7EG/view?usp=drive_web>
 MRMServer_trace.log
<https://drive.google.com/file/d/1Q05wvZW9mCsa2SGYiJv8AtatjzLDZs7g/view?usp=drive_web>



Regards,
Geetha

**Comment by anshulga** [comment]
I had a few meetings with Geetha to troubleshoot this issue. The issue turned out to be due to the usage of Oracle JDK. Geetha was able to get past the issue after switching to IBM JDK, as supported by the migration tool.

Closing the issue.
